### PR TITLE
fix a infinite recursion in the simple span batch sender

### LINKED ISSUE #85: Stack overflow when trying to use SimpleSpanBatchSender.builder(String apiKey)
it just calls itself.  🤦‍♂

### PR DESCRIPTION
**Pull request by jkwatson**
resolves #85

### CODE REVIEW

File: telemetry-http-okhttp/src/main/java/com/newrelic/telemetry/SimpleSpanBatchSender.java [hunk 1]
```diff
@@ -34,7 +34,7 @@ public static SpanBatchSender build(String apiKey) {
    *     Relic API Keys</a>
    */
   public static SpanBatchSenderBuilder builder(String apiKey) {
-    return builder(apiKey);
```
Comment (breedx-nr) [inline telemetry-http-okhttp/src/main/java/com/newrelic/telemetry/SimpleSpanBatchSender.java]: Yeah that'll do it.
