### PR TITLE
Log batch type

### LINKED ISSUE #238: Specify the type of batch that received an error and can't be sent.
Expected:

`TelemetryClient`  and `BatchDataSender` sends for all 4 Batch types and outputs logs providing visibility into the send process and if an error occurs. 

The log messages would be clear as to which of the 4 batch types it is informing about.

Currently:

The log messages in both classes are hardcoded to `metric batch type`. This is at best ambiguous or potentially incorrect as to what type of batch is experiencing issues or was successfully sent.  This makes troubleshooting more difficult. 

https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/ead77b298be355df60f98a085085387815aa7a30/telemetry/src/main/java/com/newrelic/telemetry/TelemetryClient.java#L193-L195

Fix: The error message should reflect the type of batch (metric, event, trace, log) that failed to send.

### PR DESCRIPTION
**Pull request by XiXiaPdx**
This resolves #238 

Get batch type from `batch.getClass().getSimpleName()` and apply to all relevant log messages. 

Manual testing output

```
[Thread-0] DEBUG com.newrelic.telemetry.spans.SpanBatchSender - Sending a span batch (number of spans: 1) to the New Relic span ingest endpoint)
[Thread-0] DEBUG com.newrelic.telemetry.spans.json.SpanBatchMarshaller - Generating json for span batch.
[main] DEBUG com.newrelic.telemetry.metrics.MetricBuffer - Creating metric batch.
[main] INFO com.newrelic.telemetry.TelemetryClient - Shutting down the TelemetryClient background Executor
[Thread-0] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Sending json for SpanBatch : [{"common":{"trace.id":"cbc8fcc5-6826-4961-88b3-b4a646cf7283","attributes":{"environment":"staging","service.name":"TelemetryClientExampleService","exampleName":"TelemetryClientExample","host.hostname":"C02WC0RNHTD8","instrumentation.provider":"Manual instrumentation"}},"spans":[{"id":"b77ba918-9443-43e5-a068-bd1cb8153328","trace.id":"902ceab8-6029-42b9-9eb5-11e1dd5314d0","timestamp":1607214596526,"attributes":{"duration.ms":150.0,"name":"testSpan"}}]}] 
[Thread-0] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Response from New Relic ingest API for SpanBatch: code: 202, body: {"requestId":"87b33e93-0001-b000-0000-0176357483f4"}
[Thread-0] DEBUG com.newrelic.telemetry.TelemetryClient - Telemetry - SpanBatch - sent
[Thread-0] DEBUG com.newrelic.telemetry.metrics.MetricBatchSender - Sending a metric batch (number of metrics: 5) to the New Relic metric ingest endpoint)
[Thread-0] DEBUG com.newrelic.telemetry.metrics.json.MetricBatchMarshaller - Generating json for metric batch.
[Thread-0] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Sending json for MetricBatch : [{"common":{"attributes":{"environment":"staging","service.name":"TelemetryClientExampleService","exampleName":"TelemetryClientExample","host.hostname":"C02WC0RNHTD8","instrumentation.provider":"Manual instrumentation"}},"metrics":[{"name":"temperatureC","type":"gauge","value":44.0,"timestamp":1607214596530,"attributes":{"room":"kitchen"}},{"name":"temperatureC","type":"gauge","value":25.0,"timestamp":1607214596530,"attributes":{"room":"bathroom"}},{"name":"temperatureC","type":"gauge","value":10.0,"timestamp":1607214596530,"attributes":{"room":"basement"}},{"name":"bugsSquashed","type":"count","value":5.0,"timestamp":1607214596530,"interval.ms":3,"attributes":{"project":"JAVA"}},{"name":"throughput","type":"summary","value":{"count":25,"sum":100.0,"min":1.0,"max":10.0},"timestamp":1607214596530,"interval.ms":3,"attributes":{}}]}] 
[Thread-0] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Response from New Relic ingest API for MetricBatch: code: 202, body: {"requestId":"41b19674-0024-b000-0000-0176357484d7"}
[Thread-0] DEBUG com.newrelic.telemetry.TelemetryClient - Telemetry - MetricBatch - sent
[Thread-0] DEBUG com.newrelic.telemetry.events.EventBatchSender - Sending an event batch (number of events: 1) to the New Relic event ingest endpoint)
[Thread-0] DEBUG com.newrelic.telemetry.events.json.EventBatchMarshaller - Generating json for event batch.
[Thread-0] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Sending json for EventBatch : [{"eventType":"TestEvent","timestamp":1607214596535,"environment":"staging","service.name":"TelemetryClientExampleService","exampleName":"TelemetryClientExample","testKey":"testValue","host.hostname":"C02WC0RNHTD8","instrumentation.provider":"Manual instrumentation"}] 
[Thread-0] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Response from New Relic ingest API for EventBatch: code: 200, body: {"success":true, "uuid":"ce270cfa-0021-b000-0000-0176357485a8"}
[Thread-0] DEBUG com.newrelic.telemetry.TelemetryClient - Telemetry - EventBatch - sent
[Thread-0] DEBUG com.newrelic.telemetry.logs.LogBatchSender - Sending a log batch (number of logs: 1) to the New Relic log ingest endpoint)
[Thread-0] DEBUG com.newrelic.telemetry.logs.json.LogBatchMarshaller - Generating json for log batch.
[Thread-0] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Sending json for LogBatch : [{"common":{"attributes":{"environment":"staging","service.name":"TelemetryClientExampleService","exampleName":"TelemetryClientExample","host.hostname":"C02WC0RNHTD8","instrumentation.provider":"Manual instrumentation"}},"logs":[{"timestamp":1607214596536,"attributes":{"trace.id":"902ceab8-6029-42b9-9eb5-11e1dd5314d0","log.level":"INFO","span.id":"b77ba918-9443-43e5-a068-bd1cb8153328"},"message":"Logging a message here about a span."}]}] 
[Thread-0] DEBUG com.newrelic.telemetry.transport.BatchDataSender - Response from New Relic ingest API for LogBatch: code: 202, body: {"requestId":"de04effa-0021-b000-0000-01763574867d"}
[Thread-0] DEBUG com.newrelic.telemetry.TelemetryClient - Telemetry - LogBatch - sent
```

### CODE REVIEW

File: telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java [hunk 1]
```diff
@@ -71,24 +71,25 @@ private String buildUserAgent(String additionalUserAgent) {
...
+  private byte[] generatePayload(String json, String batchType) throws DiscardBatchException {
     byte[] payload;
     try {
       payload = compressJson(json);
     } catch (IOException e) {
       logger.error(
-          "Failed to serialize the batch for sending to the ingest API. Discard batch recommended.",
+          "Failed to serialize the {} for sending to the ingest API. Discard batch recommended.",
+          batchType,
           e);
```
Comment (jack-berg) [inline telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:93]: If you the string template placeholder (i.e. `{}`), all the arguments are interpreted parameters for the string template. So in this case, the exception will no longer be included.

File: telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java [hunk 2]
```diff
@@ -132,33 +134,39 @@ private Response sendPayload(byte[] payload, UUID requestId)
...
+          "IOException (message: {}) while trying to send data to New Relic. {} retry recommended.",
+          e.getMessage(),
+          batchType);
       throw new RetryWithBackoffException(
           "IOException (message: {"
               + e.getMessage()
-              + "}) while trying to send data to New Relic. Batch retry recommended.",
+              + "}) while trying to send data to New Relic. "
+              + batchType
+              + " retry recommended.",
```
Comment (jack-berg) [inline telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:169]: This message building is cumbersome. Can we replace it with:
```
    String.format("IOException (message: %s) while trying to send data to New Relic. %s retry recommended", e.getMessage(), batchType);
```

File: telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java [hunk 3]
```diff
@@ -71,24 +71,25 @@ private String buildUserAgent(String additionalUserAgent) {
     return BASE_USER_AGENT_VALUE + " " + additionalUserAgent;
   }
 
-  public Response send(String json, UUID batchId)
+  public Response send(String json, UUID batchId, String batchType)
```
Comment (jack-berg) [inline telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:74]: Can we add Javadoc to this public method? Also, is there concern about changing the arguments of a public API? Technically, this is a breaking change.

Comment (jasonjkeller) [inline telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:74]: I would probably refactor the method signature here to `public Response send(String json, TelemetryBatch<? extends Telemetry> batch)` to just take a `TelemetryBatch` since you're getting both the `batchId` and `batchType` from the same `TelemetryBatch` object: `batch.getUuid()` and `batch.getClass().getSimpleName()`, respectively.

File: telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java [hunk 4]
```diff
@@ -103,7 +104,7 @@ public Response send(String json, UUID batchId)
     return compressedOutput.toByteArray();
   }
 
-  private Response sendPayload(byte[] payload, UUID requestId)
+  private Response sendPayload(byte[] payload, UUID requestId, String batchType)
```
Comment (jasonjkeller) [inline telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:107]: Same method signature refactoring would apply here.

File: telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java (hunk 3 above)
Comment (jasonjkeller) [reply telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:74]: That's a good point. I suppose we could add a new overloaded method or something to maintain backwards compatibility though that wouldn't force users to use the new API that adds the improved logging. Also, adding a new method just to get different logging output is not great now that I think about.

That said, given that this is largely an internal SDK used by us to build exporters I think we should have some leeway to make breaking changes as long as they're documented in the release notes.

Comment (jack-berg) [reply telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:74]: Any insight why its a public method instead of package private?

Comment (jasonjkeller) [reply telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:74]: Not really, unfortunately.

**Comment by XiXiaPdx** [comment]
@jasonjkeller @jack-berg  Thanks for the feedback, very helpful. I'll take another swing at it

File: telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java (hunk 1 above)
Comment (XiXiaPdx) [reply telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:93]: I tested this again and the exception and stack trace is logged. By "included", I believe you are referring to the exception and its stack trace being logged?

Comment (jack-berg) [reply telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:93]: Yes. The previous method signature being invoked was:
```
void error(String msg, Throwable t);
```
Which takes the throwable and logs information about it (i.e. the stack trace).

The new call invokes:
```
error(String format, Object arg1, Object arg2)
```
Which is different than the previous behavior. It will try to format the `format` arg using the given args, normally replacing each `{}` with `argN.toString()`.

Comment (XiXiaPdx) [reply telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:97]: Ok, resolved.

File: telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java (hunk 3 above)
Comment (XiXiaPdx) [reply telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java]: I changed the signature.

Comment (XiXiaPdx) [reply telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java]: I'll need to add a javadoc and also update the changelog

**Comment by XiXiaPdx** [comment]
@jack-berg @jasonjkeller  I added the javadoc and made the changes. If it looks good, I'll fix the merge conflicts and go from there.  

It looks like we are trying to release a new version this week so it would be good to get this in there as well

File: telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java [hunk 5]
```diff
@@ -71,24 +73,39 @@ private String buildUserAgent(String additionalUserAgent) {
...
+   * Sends a compressed byte[] of telemetry to New Relic
+   *
+   * @param json The json to send.
+   * @param batch The batch of telemetry the json was generated from
+   * @return The response from the ingest API.
+   * @throws RetryWithBackoffException Is the default case if the Ingest API responds with an error.
+   * @throws DiscardBatchException In cases where the Ingest API responds with a 411.
+   * @throws RetryWithSplitException In cases where the Ingest API responds with a 413.
+   * @throws RetryWithRequestedWaitException In cases where the Ingest API responds with a 429.
+   *
```
Comment (jack-berg) [inline telemetry-core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java:86]:
```suggestion
```
Extra blank comment line.

**Review by jack-berg — APPROVED** [review]

**Comment by XiXiaPdx** [comment]
@jack-berg  There was a merge conflict with merged PR #255.  This is when I discovered the LoggingNotificationHandler and I like how it could be a central place to specify the batch type for the log message. 

So I pivoted and made a change. It's isolated to the LoggigingNotificationHandler and messages in TelemetryClient.  Since this is after you approved and I thought you should know if you want to take a look.  Apologies for asking you to review it again!

**Comment by jack-berg** [comment]
@XiXiaPdx I see all the original changes in `EventBatchSender`.... Is this your intent?

**Comment by XiXiaPdx** [comment]
> @XiXiaPdx I see all the original changes in `EventBatchSender`.... Is this your intent?

@jack-berg  Sorry, I should be more clear. 

The change is only in `LoggingNotificationHandler` and `TelemetryClient`.  The notification handler is now handling all error log messages in the TelemetryClient. It takes the message string and batch, and then logs it.  In the `LoggingNotificationHandler`,  I'm adding the batch type to the generic message string before it is logged.

Before, I was using  formatting each log message in the `TelemetryClient` and adding the batch type with `batch.getClass().getSimpleName()` .  This approach seemed better.

**Comment by jack-berg** [comment]
Makes sense @XiXiaPdx. Merge when ready!
